---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 2 * *"

env:
    BATS_LIB_PATH: /usr/local/lib/bats
    DEBIAN_FRONTEND: noninteractive

jobs:
  make-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git make bash parallel
      - name: Install bats
        run: |
          git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
          cd /tmp/bats-core
          sudo ./install.sh /usr/local
      - name: Install bats-support
        run: sudo git clone https://github.com/bats-core/bats-support.git ${BATS_LIB_PATH}/bats-support
      - name: Install bats-assert
        run: sudo git clone https://github.com/bats-core/bats-assert.git ${BATS_LIB_PATH}/bats-assert
      - name: Install bats-file
        run: sudo git clone https://github.com/bats-core/bats-file.git ${BATS_LIB_PATH}/bats-file
      - name: Install bats-alimektor
        run: sudo git clone https://github.com/Alimektor/bats-alimektor.git ${BATS_LIB_PATH}/bats-alimektor
      - name: Run make test
        run: make test
